# Site settings
title: BMC Research Informatics Data Dictionary
email: cdw@bmc.org
description: Start here.
baseurl: "/data-guide"
repository: "https://research-informatics.github.io/data-guide/"
permalinks: pretty
defaults:
  -
    scope:
      path: "" # Apply to all files
    values:
      layout: "default"

# Build settings
markdown: kramdown
highlighter: rouge

# Add your custom CSS
include:
  - assets/css/main.css  # Add your CSS file path here

sass:
  style: compressed
